export const industryScenes = [
  {
    id: 'intro',
    label: 'The next industries will fly.',
    subline: 'Most people will notice it late.',
    modelPath: '/models/response-drone.glb',
    modelScale: 1.18,
    modelRotation: [0.08, -0.45, 0],
    camera: [-3.4, 1.45, 5.2],
    lookAt: [0.25, 0.05, 0],
  },
  {
    id: 'agriculture',
    label: 'Agriculture',
    subline: 'Crop scan. Spray route. Repeatable precision.',
    modelPath: '/models/agriculture-drone.glb',
    modelScale: 1.28,
    modelRotation: [0.02, 0.72, 0],
    camera: [-4.4, 2.05, 5.8],
    lookAt: [0.15, -0.1, -0.2],
  },
  {
    id: 'inspection',
    label: 'Inspection',
    subline: 'Orbit close. Read structure. Find risk early.',
    modelPath: '/models/inspection-drone.glb',
    modelScale: 1.12,
    modelRotation: [0.04, -0.62, 0],
    camera: [3.9, 1.65, 5.1],
    lookAt: [-0.15, 0.05, 0],
  },
  {
    id: 'response',
    label: 'Response',
    subline: 'Sweep terrain. Detect heat. Move before roads reopen.',
    modelPath: '/models/response-drone.glb',
    modelScale: 1.22,
    modelRotation: [0.04, 0.15, 0],
    camera: [-3.55, 1.8, 5.35],
    lookAt: [0.1, -0.05, -0.2],
  },
  {
    id: 'logistics',
    label: 'Logistics',
    subline: 'Route locked. Payload carried. City distance compressed.',
    modelPath: '/models/logistics-drone.glb',
    modelScale: 1.22,
    modelRotation: [0, -0.2, 0],
    camera: [4.1, 1.9, 5.4],
    lookAt: [0.1, -0.05, -0.1],
  },
  {
    id: 'mapping',
    label: 'Mapping',
    subline: 'Pulse ground. Build contours. Turn terrain into data.',
    modelPath: '/models/mapping-drone.glb',
    modelScale: 1.18,
    modelRotation: [0.06, 0.52, 0],
    camera: [-3.9, 2.2, 5.55],
    lookAt: [0.05, -0.1, -0.15],
  },
  {
    id: 'security',
    label: 'Security',
    subline: 'Patrol perimeter. Watch patterns. Stay present.',
    modelPath: '/models/security-drone.glb',
    modelScale: 1.1,
    modelRotation: [0.04, -0.52, 0],
    camera: [3.75, 1.65, 5.3],
    lookAt: [0.05, -0.05, -0.15],
  },
  {
    id: 'final',
    label: 'Everything complex begins from one simple principle.',
    subline: 'See The Philosophy',
    modelPath: '/models/mapping-drone.glb',
    modelScale: 1.05,
    modelRotation: [0.08, -0.85, 0],
    camera: [0, 1.65, 5.6],
    lookAt: [0, 0, 0],
  },
];
